services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  catalogue:
    image: catalogu:v1
    depends_on: mongodb
    container_name: catalogue


networks:
  default:
    driver: bridge
    name: roboshop
    external: true

